# Generated by Django 6.0 on 2025-12-23 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_experiencialaboral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconocimientos',
            fields=[
                ('idreconocimiento', models.IntegerField(primary_key=True, serialize=False)),
                ('tiporeconocimiento', models.CharField(choices=[('Academico', 'Académico'), ('Laboral', 'Laboral'), ('Institucional', 'Institucional')], max_length=100)),
                ('fechareconocimiento', models.DateField()),
                ('descripcionreconocimiento', models.CharField(max_length=100)),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('nombrecontactoauspicia', models.CharField(max_length=100)),
                ('telefonocontactoauspicia', models.CharField(max_length=60)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(max_length=100)),
                ('idperfilconqueestaactivo', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='perfil.datospersonales')),
            ],
            options={
                'db_table': 'RECONOCIMIENTOS',
            },
        ),
    ]
